Exception occurred at 2023-11-20 14:07:45:
java.io.FileNotFoundException: src/resources/database.properties (Нет такого файла или каталога)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at services.ConnectionPool.initializePool(ConnectionPool.java:30)
	at services.ConnectionPool.<clinit>(ConnectionPool.java:25)
	at DAO.LibraryBookDAO.getAllBooks(LibraryBookDAO.java:42)
	at services.Library.booksToString(Library.java:142)
	at Main.main(Main.java:21)
Exception occurred at 2023-11-20 14:55:12:
java.io.FileNotFoundException: src/resources.scripts/database.properties (Нет такого файла или каталога)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at services.ConnectionPool.initializePool(ConnectionPool.java:30)
	at services.ConnectionPool.<clinit>(ConnectionPool.java:25)
	at DAO.LibraryBookDAO.getAllBooks(LibraryBookDAO.java:42)
	at services.Library.booksToString(Library.java:142)
	at Main.main(Main.java:21)
Exception occurred at 2023-11-20 14:57:19:
java.io.FileNotFoundException: src/scripts/database.properties (Нет такого файла или каталога)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at services.ConnectionPool.initializePool(ConnectionPool.java:30)
	at services.ConnectionPool.<clinit>(ConnectionPool.java:25)
	at DAO.LibraryBookDAO.getAllBooks(LibraryBookDAO.java:42)
	at services.Library.booksToString(Library.java:142)
	at Main.main(Main.java:21)
Exception occurred at 2023-11-20 15:46:11:
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "librarybooks_pkey"
  Подробности: Key (bookid)=(5) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
	at DAO.LibraryBookDAO.addBook(LibraryBookDAO.java:30)
	at services.Library.addBook(Library.java:50)
	at Main.main(Main.java:27)
Exception occurred at 2023-11-20 15:46:11:
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "librarybooks_pkey"
  Подробности: Key (bookid)=(6) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
	at DAO.LibraryBookDAO.addBook(LibraryBookDAO.java:30)
	at services.Library.addBook(Library.java:50)
	at Main.main(Main.java:35)
Exception occurred at 2023-11-20 15:46:11:
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "readers_pkey"
  Подробности: Key (readerid)=(4) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:135)
	at DAO.ReaderDAO.addReader(ReaderDAO.java:28)
	at services.Library.addReader(Library.java:54)
	at Main.main(Main.java:46)
